version: '3.8'

services:
  app: # php (laravel API): アプリケーションサーバー
    container_name: app_attendance
    build:
      context: .
      dockerfile: ./docker/back/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - ${APP_PORT}:8000
    tty: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  web: # nginx: webサーバー
    container_name: web_attendance
    build:
      context: .
      dockerfile: ./docker/back/nginx/Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - ${WEB_PORT}:80
    tty: true
    restart: always
    depends_on:
      - frontend
      - app

  frontend: # nuxt3: フロントエンド
    container_name: frontend_attendance
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - ./frontend:/var/www/src
    ports:
      - ${FRONT_PORT}:3000
      - 24678:24678 # ホットリロード用のポート
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true # nuxtのホットリロード有効化
  
  # mysqlの設定
  db:
    container_name: mysql_attendance
    build:
      context: .
      dockerfile: ./docker/back/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db:/var/lib/mysql
